#!/bin/bash

text_to_speech() {
    local text="$1"
    curl -X POST \
         -H 'xi-api-key: ""' \
         -H 'Content-Type: application/json' \
         -d '{"model_id":"eleven_multilingual_v2","text":"'"$text"'","voice_settings":{"stability":1,"similarity_boost":0}}' \
         'https://api.elevenlabs.io/v1/text-to-speech/TxGEqnHWrfWFTfGW9XjX?optimize_streaming_latency=3&output_format=mp3_44100_32' \
         | mpg123 -
}

text_to_speech "$1"

