palette = 0=#term0#
palette = 1=#term1#
palette = 2=#term2#
palette = 3=#term3#
palette = 4=#term4#
palette = 5=#term5#
palette = 6=#term6#
palette = 7=#term7#
palette = 8=#term8#
palette = 9=#term9#
palette = 10=#term10#
palette = 11=#term11#
palette = 12=#term12#
palette = 13=#term13#
palette = 14=#term14#
palette = 15=#term15#
background=#background#
foreground=#onBackground#
font-family=JetBrainsMono Nerd Font
